# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TabBarController' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TabBarController

  target 'TabBarController_iOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TabBarController_iOSUITests' do
    # Pods for testing
  end

  target 'TabBarControllerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TabBarControllerUITests' do
    # Pods for testing
  end

end

target 'TabBarController_iOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TabBarController_iOS

  target 'TabBarController_iOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TabBarController_iOSUITests' do
    # Pods for testing
  end

end
