# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

source 'https://zrepository.zoho.com/zohocorp/zoho/zohopodspecs.git'

target 'PackageTest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  # Pods for PackageTest
  pod 'ZMacAuth', '1.0.4-beta2'
  
end

target 'PackageTest-iOS' do
  use_frameworks!
  pod 'SSOKit', '2.0.16'
end
